import { TextFormatter } from '../common/textformatter';
import { SuiApplication } from './application';
import { SuiEventHandler } from './eventHandler';
import { SuiExceptionHandler } from '../ui/exceptions';
import { Qwerty } from '../ui/qwerty';
import { SuiPiano } from '../render/sui/piano';
import { SuiDom } from './dom';
import { SuiHelp } from '../ui/help';
import { CollapseRibbonControl, ExtendedCollapseParent } from '../ui/buttons/collapsable';
import { DisplaySettings } from '../ui/buttons/display';
import { SmoTranslationEditor } from '../ui/i18n/translationEditor';
import { SmoConfiguration } from './configuration';
import { RibbonButtons } from '../ui/buttons/ribbon';
import { simpleRibbonLayout } from '../ui/ribbonLayout/default/tabletRibbon';
import { ModalEventHandler } from './common';
import { SuiDialogBase } from '../ui/dialogs/dialog';
import { SuiGraceNoteAdapter, SuiGraceNoteDialog, SuiGraceNoteButtonsComponent } from '../ui/dialogs/gracenote';
import { SuiModifierDialogFactory } from '../ui/dialogs/factory';
import { SuiTransposeScoreDialog, SuiTransposeScoreAdapter } from '../ui/dialogs/transposeScore';
import { SuiMeasureDialog } from '../ui/dialogs/measureFormat';
import { SuiInsertMeasures } from '../ui/dialogs/addMeasure';
import { SuiInstrumentDialog } from '../ui/dialogs/instrument';
import { SuiTimeSignatureDialog } from '../ui/dialogs/timeSignature';
import { SuiTempoDialog } from '../ui/dialogs/tempo';
import { SuiNoteHeadAdapter, SuiNoteHeadDialog, SuiNoteHeadButtonComponent, SuiStemButtonComponent } from '../ui/dialogs/noteHead';
import { SuiEndingsAdapter, SuiEndingsDialog, SuiEndBarButtonComponent, SuiStartBarButtonComponent, SuiRepeatSymbolButtonComponent } from '../ui/dialogs/endings';
import { SuiScoreIdentificationDialog } from '../ui/dialogs/scoreId';
import { SuiScorePreferencesDialog } from '../ui/dialogs/preferences';
import { SuiPageLayoutDialog } from '../ui/dialogs/pageLayout';
import { SuiTextBracketDialog } from '../ui/dialogs/textBracket';
import { SuiScoreFontDialog } from '../ui/dialogs/fonts';
import { SuiGlobalLayoutDialog } from '../ui/dialogs/globalLayout';
import { SuiScoreViewDialog } from '../ui/dialogs/scoreView';
import { SuiLibraryDialog } from '../ui/dialogs/library';
import { SuiChordChangeDialog } from '../ui/dialogs/chordChange';
import { SuiLyricDialog } from '../ui/dialogs/lyric';
import { SuiTextBlockDialog, helpModal } from '../ui/dialogs/textBlock';
import { SuiDynamicModifierDialog } from '../ui/dialogs/dynamics';
import { SuiSlurAttributesDialog } from '../ui/dialogs/slur';
import { SuiPedalMarkingDialog } from '../ui/dialogs/pedalMarking';
import { SuiTieAttributesDialog } from '../ui/dialogs/tie';
import { SuiVoltaAttributeDialog } from '../ui/dialogs/volta';
import { SuiHairpinAttributesDialog } from '../ui/dialogs/hairpin';
import { SuiStaffGroupDialog } from '../ui/dialogs/staffGroup';
import { SuiOrnamentDialog, SuiOrnamentButtonComponent } from '../ui/dialogs/ornament';
import { SuiArticulationDialog, SuiArticulationButtonComponent, SuiArticulationAdapter } from '../ui/dialogs/articulation';
import { SuiMicrotoneAdapter, SuiMicrotoneButtonComponent, SuiMicrotoneDialog } from '../ui/dialogs/microtones';
import { SuiArpeggioDialog } from '../ui/dialogs/arpeggio';
import { SuiClefChangeDialog } from '../ui/dialogs/clefChange';
import { SuiPartInfoDialog } from '../ui/dialogs/partInfo';
import { SuiLoadMxmlDialog, SuiLoadFileDialog, SuiPrintFileDialog, SuiSaveFileDialog, SuiSaveXmlDialog, SuiSaveMidiDialog, SuiSaveVexDialog } from '../ui/dialogs/fileDialogs';
import { SuiTextInputComponent, SuiTextInputComposite, SuiReadOnlyTextComponent } from '../ui/dialogs/components/textInput';
import { SuiDropdownComponent, SuiDropdownComposite } from '../ui/dialogs/components/dropdown';
import { SuiButtonComposite, SuiButtonComponent } from '../ui/dialogs/components/button';
import { SuiButtonArrayComponent, SuiButtonArrayMSComponent } from '../ui/dialogs/components/buttonArray';
import { SuiToggleComponent, SuiToggleComposite } from '../ui/dialogs/components/toggle';
import { SuiFileDownloadComponent } from '../ui/dialogs/components/fileDownload';
import { SuiRockerComponent, SuiRockerComposite } from '../ui/dialogs/components/rocker';
import { SuiFontComponent } from '../ui/dialogs/components/fontComponent';
import { SuiTextBlockComponent } from '../ui/dialogs/components/textInPlace';
import { SuiTreeComponent } from '../ui/dialogs/components/tree';
import { SuiPitchArrayComponent, SuiPitchArrayComponentTab, SuiPitchComponent, SuiPitchComposite } from '../ui/dialogs/components/pitch';
import { SuiLyricComponent, SuiChordComponent, SuiNoteTextComponent } from '../ui/dialogs/components/noteText';
import { SuiDragText } from '../ui/dialogs/components/dragText';
import { SuiTextInPlace } from '../ui/dialogs/components/textInPlace';
import { CheckboxDropdownComponent } from '../ui/dialogs/components/checkdrop';
import { TieMappingComponent } from '../ui/dialogs/components/tie';
import { StaffAddRemoveComponent, StaffCheckComponent } from '../ui/dialogs/components/staffComponents';
import { SuiKeySignatureDialog, SuiKeySignatureAdapter } from '../ui/dialogs/keySignature';
import { TextCheckComponent } from '../ui/dialogs/components/textCheck';
import { SuiMenuManager } from '../ui/menus/manager';
import { SuiMenuBase } from '../ui/menus/menu';
import { SuiScoreMenu } from '../ui/menus/score';
import { SuiTextMenu } from '../ui/menus/text';
import { SuiPartMenu } from '../ui/menus/parts';
import { SuiVoiceMenu } from '../ui/menus/voices';
import { SuiBeamMenu } from '../ui/menus/beams';
import { SuiPartSelectionMenu } from '../ui/menus/partSelection';
import { SuiDynamicsMenu } from '../ui/menus/dynamics';
import { SuiTimeSignatureMenu } from '../ui/menus/timeSignature';
import { SuiKeySignatureMenu } from '../ui/menus/keySignature';
import { SuiStaffModifierMenu } from '../ui/menus/staffModifier';
import { SuiFileMenu } from '../ui/menus/file';
import { SuiLanguageMenu } from '../ui/menus/language';
import { SmoLanguage, SmoTranslator } from '../ui/i18n/language';
import { SuiMeasureMenu } from '../ui/menus/measure';
import { SuiNoteMenu } from '../ui/menus/note';
import { SuiXhrLoader } from '../ui/fileio/xhrLoader';
import { PromiseHelpers } from '../common/promiseHelpers';
import { SuiScoreView } from '../render/sui/scoreView';
import { SuiScoreViewOperations } from '../render/sui/scoreViewOperations';
import { SuiScoreRender } from '../render/sui/scoreRender';
import { layoutDebug } from '../render/sui/layoutDebug';
import { SuiMapper } from '../render/sui/mapper';
import { SuiScroller } from '../render/sui/scroller';
import { SvgHelpers } from '../render/sui/svgHelpers';
import { SuiAudioPlayer } from '../render/audio/player';
import { SuiOscillator, SuiSampler, SuiReverb } from '../render/audio/oscillator';
import { SuiSampleMedia } from '../render/audio/samples';
import { SmoScore, isEngravingFont } from '../smo/data/score';
import { UndoBuffer } from '../smo/xform/undo';
import { SmoNote } from '../smo/data/note';
import { createLoadTests } from '../../tests/file-load';
import { SmoStaffHairpin, StaffModifierBase, SmoInstrument, SmoSlur, SmoTie, SmoStaffTextBracket, SmoTabStave, SmoPedalMarking } from '../smo/data/staffModifiers';
import { SmoMeasure } from '../smo/data/measure';
import { SmoMusic } from '../smo/data/music';
import { SmoAudioPitch } from '../smo/data/music';
import { SmoSelection, SmoSelector } from '../smo/xform/selections';
import { SmoOrnament, SmoArticulation, SmoDynamicText, SmoGraceNote, SmoMicrotone, SmoLyric, SmoArpeggio, SmoClefChange } from '../smo/data/noteModifiers';
import { SmoSystemStaff } from '../smo/data/systemStaff';
import { SmoSystemGroup, SmoAudioPlayerSettings, SmoScorePreferences } from '../smo/data/scoreModifiers';
import { SmoTextGroup } from '../smo/data/scoreText';
import { SmoOperation } from '../smo/xform/operations';
import { SmoRehearsalMark, SmoMeasureFormat, SmoBarline, SmoRepeatSymbol, SmoVolta, SmoMeasureText, SmoTempoText, TimeSignature } from '../smo/data/measureModifiers';
import { SmoToXml } from '../smo/mxml/smoToXml';
import { MidiToSmo } from '../smo/midi/midiToSmo';
import { SmoToMidi } from '../smo/midi/smoToMidi';
import { XmlToSmo } from '../smo/mxml/xmlToSmo';
import { SmoToVex } from '../render/vex/toVex';
import { buildDom, addFileLink, InputTrapper, draggable, closeDialogPromise, getDomContainer, createTopDomContainer } from '../common/htmlHelpers';
import { renderVexTests } from './generateVexTests';
import { SuiDurationAdapter, SuiDurationButtonComponent, SuiDurationDialog } from '../ui/dialogs/durations';
import { SuiPitchAdapter, SuiPitchDialog, SuiLetterButtonComponent, SuiIntervalButtonComponent, SuiTransposeButtonComponent } from '../ui/dialogs/pitch';
export declare const Smo: {
    SmoConfiguration: typeof SmoConfiguration;
    SuiApplication: typeof SuiApplication;
    SuiDom: typeof SuiDom;
    SuiEventHandler: typeof SuiEventHandler;
    SuiExceptionHandler: typeof SuiExceptionHandler;
    Qwerty: typeof Qwerty;
    SuiHelp: typeof SuiHelp;
    SmoTranslationEditor: typeof SmoTranslationEditor;
    ModalEventHandler: typeof ModalEventHandler;
    simpleRibbonLayout: typeof simpleRibbonLayout;
    RibbonButtons: typeof RibbonButtons;
    DisplaySettings: typeof DisplaySettings;
    ExtendedCollapseParent: typeof ExtendedCollapseParent;
    CollapseRibbonControl: typeof CollapseRibbonControl;
    SuiMenuManager: typeof SuiMenuManager;
    SuiMenuBase: typeof SuiMenuBase;
    SuiScoreMenu: typeof SuiScoreMenu;
    SuiFileMenu: typeof SuiFileMenu;
    SuiDynamicsMenu: typeof SuiDynamicsMenu;
    SuiTimeSignatureMenu: typeof SuiTimeSignatureMenu;
    SuiKeySignatureMenu: typeof SuiKeySignatureMenu;
    SuiStaffModifierMenu: typeof SuiStaffModifierMenu;
    SuiLanguageMenu: typeof SuiLanguageMenu;
    SuiMeasureMenu: typeof SuiMeasureMenu;
    SuiNoteMenu: typeof SuiNoteMenu;
    SmoLanguage: typeof SmoLanguage;
    SmoTranslator: typeof SmoTranslator;
    SuiPartMenu: typeof SuiPartMenu;
    SuiPartSelectionMenu: typeof SuiPartSelectionMenu;
    SuiTextMenu: typeof SuiTextMenu;
    SuiVoiceMenu: typeof SuiVoiceMenu;
    SuiBeamMenu: typeof SuiBeamMenu;
    SuiGraceNoteAdapter: typeof SuiGraceNoteAdapter;
    SuiGraceNoteDialog: typeof SuiGraceNoteDialog;
    SuiGraceNoteButtonsComponent: typeof SuiGraceNoteButtonsComponent;
    SuiDurationAdapter: typeof SuiDurationAdapter;
    SuiDurationDialog: typeof SuiDurationDialog;
    SuiDurationButtonComponent: typeof SuiDurationButtonComponent;
    SuiTempoDialog: typeof SuiTempoDialog;
    SuiInstrumentDialog: typeof SuiInstrumentDialog;
    SuiModifierDialogFactory: typeof SuiModifierDialogFactory;
    SuiLibraryDialog: typeof SuiLibraryDialog;
    SuiTextBracketDialog: typeof SuiTextBracketDialog;
    SuiKeySignatureDialog: typeof SuiKeySignatureDialog;
    SuiKeySignatureAdapter: typeof SuiKeySignatureAdapter;
    SuiScoreViewDialog: typeof SuiScoreViewDialog;
    SuiGlobalLayoutDialog: typeof SuiGlobalLayoutDialog;
    SuiScoreIdentificationDialog: typeof SuiScoreIdentificationDialog;
    SuiTransposeScoreAdapter: typeof SuiTransposeScoreAdapter;
    SuiTransposeScoreDialog: typeof SuiTransposeScoreDialog;
    SuiScoreFontDialog: typeof SuiScoreFontDialog;
    SuiPageLayoutDialog: typeof SuiPageLayoutDialog;
    SuiMeasureDialog: typeof SuiMeasureDialog;
    SuiInsertMeasures: typeof SuiInsertMeasures;
    SuiTimeSignatureDialog: typeof SuiTimeSignatureDialog;
    SuiTextBlockDialog: typeof SuiTextBlockDialog;
    SuiLyricDialog: typeof SuiLyricDialog;
    SuiChordChangeDialog: typeof SuiChordChangeDialog;
    SuiSlurAttributesDialog: typeof SuiSlurAttributesDialog;
    SuiPedalMarkingDialog: typeof SuiPedalMarkingDialog;
    SuiTieAttributesDialog: typeof SuiTieAttributesDialog;
    SuiVoltaAttributeDialog: typeof SuiVoltaAttributeDialog;
    SuiHairpinAttributesDialog: typeof SuiHairpinAttributesDialog;
    SuiStaffGroupDialog: typeof SuiStaffGroupDialog;
    helpModal: typeof helpModal;
    SuiLoadFileDialog: typeof SuiLoadFileDialog;
    SuiLoadMxmlDialog: typeof SuiLoadMxmlDialog;
    SuiScorePreferencesDialog: typeof SuiScorePreferencesDialog;
    SuiPartInfoDialog: typeof SuiPartInfoDialog;
    SuiOrnamentDialog: typeof SuiOrnamentDialog;
    SuiOrnamentButtonComponent: typeof SuiOrnamentButtonComponent;
    SuiArticulationDialog: typeof SuiArticulationDialog;
    SuiArticulationButtonComponent: typeof SuiArticulationButtonComponent;
    SuiArticulationAdapter: typeof SuiArticulationAdapter;
    SuiMicrotoneAdapter: typeof SuiMicrotoneAdapter;
    SuiMicrotoneButtonComponent: typeof SuiMicrotoneButtonComponent;
    SuiMicrotoneDialog: typeof SuiMicrotoneDialog;
    SuiNoteHeadAdapter: typeof SuiNoteHeadAdapter;
    SuiNoteHeadDialog: typeof SuiNoteHeadDialog;
    SuiStemButtonComponent: typeof SuiStemButtonComponent;
    SuiNoteHeadButtonComponent: typeof SuiNoteHeadButtonComponent;
    SuiEndingsAdapter: typeof SuiEndingsAdapter;
    SuiEndingsDialog: typeof SuiEndingsDialog;
    SuiEndBarButtonComponent: typeof SuiEndBarButtonComponent;
    SuiStartBarButtonComponent: typeof SuiStartBarButtonComponent;
    SuiRepeatSymbolButtonComponent: typeof SuiRepeatSymbolButtonComponent;
    SuiPrintFileDialog: typeof SuiPrintFileDialog;
    SuiSaveFileDialog: typeof SuiSaveFileDialog;
    SuiSaveXmlDialog: typeof SuiSaveXmlDialog;
    SuiSaveVexDialog: typeof SuiSaveVexDialog;
    SuiSaveMidiDialog: typeof SuiSaveMidiDialog;
    SuiDialogBase: typeof SuiDialogBase;
    SuiPitchDialog: typeof SuiPitchDialog;
    SuiPitchAdapter: typeof SuiPitchAdapter;
    SuiIntervalButtonComponent: typeof SuiIntervalButtonComponent;
    SuiLetterButtonComponent: typeof SuiLetterButtonComponent;
    SuiTransposeButtonComponent: typeof SuiTransposeButtonComponent;
    SuiTreeComponent: typeof SuiTreeComponent;
    SuiDropdownComponent: typeof SuiDropdownComponent;
    SuiRockerComponent: typeof SuiRockerComponent;
    SuiFileDownloadComponent: typeof SuiFileDownloadComponent;
    SuiButtonArrayComponent: typeof SuiButtonArrayComponent;
    SuiButtonArrayMSComponent: typeof SuiButtonArrayMSComponent;
    SuiToggleComponent: typeof SuiToggleComponent;
    SuiButtonComponent: typeof SuiButtonComponent;
    SuiDropdownComposite: typeof SuiDropdownComposite;
    SuiToggleComposite: typeof SuiToggleComposite;
    SuiButtonComposite: typeof SuiButtonComposite;
    SuiRockerComposite: typeof SuiRockerComposite;
    SuiTextInputComposite: typeof SuiTextInputComposite;
    SuiFontComponent: typeof SuiFontComponent;
    SuiTextInPlace: typeof SuiTextInPlace;
    SuiLyricComponent: typeof SuiLyricComponent;
    SuiChordComponent: typeof SuiChordComponent;
    SuiDragText: typeof SuiDragText;
    SuiNoteTextComponent: typeof SuiNoteTextComponent;
    SuiTextBlockComponent: typeof SuiTextBlockComponent;
    SuiTextInputComponent: typeof SuiTextInputComponent;
    SuiReadOnlyTextComponent: typeof SuiReadOnlyTextComponent;
    SuiDynamicModifierDialog: typeof SuiDynamicModifierDialog;
    CheckboxDropdownComponent: typeof CheckboxDropdownComponent;
    TieMappingComponent: typeof TieMappingComponent;
    StaffAddRemoveComponent: typeof StaffAddRemoveComponent;
    StaffCheckComponent: typeof StaffCheckComponent;
    TextCheckComponent: typeof TextCheckComponent;
    SuiArpeggioDialog: typeof SuiArpeggioDialog;
    SuiClefChangeDialog: typeof SuiClefChangeDialog;
    SuiPitchArrayComponent: typeof SuiPitchArrayComponent;
    SuiPitchArrayComponentTab: typeof SuiPitchArrayComponentTab;
    SuiPitchComponent: typeof SuiPitchComponent;
    SuiPitchComposite: typeof SuiPitchComposite;
    SuiXhrLoader: typeof SuiXhrLoader;
    PromiseHelpers: typeof PromiseHelpers;
    SuiPiano: typeof SuiPiano;
    layoutDebug: typeof layoutDebug;
    SuiScoreView: typeof SuiScoreView;
    SuiScroller: typeof SuiScroller;
    SvgHelpers: typeof SvgHelpers;
    SuiMapper: typeof SuiMapper;
    SuiScoreRender: typeof SuiScoreRender;
    SuiScoreViewOperations: typeof SuiScoreViewOperations;
    TextFormatter: typeof TextFormatter;
    VexFlow: typeof import("vexflow_smoosic").Flow;
    SuiAudioPlayer: typeof SuiAudioPlayer;
    SuiOscillator: typeof SuiOscillator;
    SuiSampleMedia: typeof SuiSampleMedia;
    SuiSampler: typeof SuiSampler;
    SuiReverb: typeof SuiReverb;
    SmoScore: typeof SmoScore;
    SmoScorePreferences: typeof SmoScorePreferences;
    engravingFontTypes: import("../smo/data/score").engravingFontType[];
    isEngravingFont: typeof isEngravingFont;
    XmlToSmo: typeof XmlToSmo;
    SmoToXml: typeof SmoToXml;
    MidiToSmo: typeof MidiToSmo;
    SmoToMidi: typeof SmoToMidi;
    SmoMusic: typeof SmoMusic;
    SmoAudioPitch: typeof SmoAudioPitch;
    SmoMeasure: typeof SmoMeasure;
    SmoSystemStaff: typeof SmoSystemStaff;
    SmoNote: typeof SmoNote;
    SmoStaffHairpin: typeof SmoStaffHairpin;
    StaffModifierBase: typeof StaffModifierBase;
    SmoStaffTextBracket: typeof SmoStaffTextBracket;
    SmoInstrument: typeof SmoInstrument;
    SmoSlur: typeof SmoSlur;
    SmoPedalMarking: typeof SmoPedalMarking;
    SmoTie: typeof SmoTie;
    SmoTabStave: typeof SmoTabStave;
    SmoSystemGroup: typeof SmoSystemGroup;
    SmoAudioPlayerSettings: typeof SmoAudioPlayerSettings;
    SmoTextGroup: typeof SmoTextGroup;
    SmoRehearsalMark: typeof SmoRehearsalMark;
    SmoMeasureFormat: typeof SmoMeasureFormat;
    SmoBarline: typeof SmoBarline;
    SmoRepeatSymbol: typeof SmoRepeatSymbol;
    SmoVolta: typeof SmoVolta;
    SmoMeasureText: typeof SmoMeasureText;
    SmoTempoText: typeof SmoTempoText;
    TimeSignature: typeof TimeSignature;
    SmoOrnament: typeof SmoOrnament;
    SmoArticulation: typeof SmoArticulation;
    SmoDynamicText: typeof SmoDynamicText;
    SmoGraceNote: typeof SmoGraceNote;
    SmoMicrotone: typeof SmoMicrotone;
    SmoLyric: typeof SmoLyric;
    SmoArpeggio: typeof SmoArpeggio;
    SmoClefChange: typeof SmoClefChange;
    SmoSelection: typeof SmoSelection;
    SmoSelector: typeof SmoSelector;
    UndoBuffer: typeof UndoBuffer;
    SmoToVex: typeof SmoToVex;
    SmoOperation: typeof SmoOperation;
    cardKeysHtmlEn: string;
    cardNotesLetterHtmlEn: string;
    cardNotesChromaticHtmlEn: string;
    cardNotesChordsHtmlEn: string;
    cardNotesRestsHtmlEn: string;
    cardDurationNotesHtmlEn: string;
    cardDurationTupletsHtmlEn: string;
    cardSelectionsNotesHtmlEn: string;
    cardSelectionsModifiersHtmlEn: string;
    cardSelectionsNonSelectableHtmlEn: string;
    cardSelectionsSlashHtmlEn: string;
    cardBeamsAndStemsDirectionHtmlEn: string;
    cardBeamsAndStemsGroupingHtmlEn: string;
    cardMeasuresAddDeleteHtmlEn: string;
    cardVoicesCreateDeleteHtmlEn: string;
    cardPartAddDeleteHtmlEn: string;
    getClass: (jsonString: string) => any;
    createLoadTests: typeof createLoadTests;
    buildDom: typeof buildDom;
    addFileLink: typeof addFileLink;
    InputTrapper: typeof InputTrapper;
    draggable: typeof draggable;
    closeDialogPromise: typeof closeDialogPromise;
    getDomContainer: typeof getDomContainer;
    createTopDomContainer: typeof createTopDomContainer;
    renderVexTests: typeof renderVexTests;
};
export default Smo;
//# sourceMappingURL=exports.d.ts.map